# -*- coding: utf-8 -*-
"""Exceptional Handling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wuyW67xJxQM-T5oNwgjJ1Dek-ACthY6
"""

print( dir(__builtins__) )

import lkjhfasd

print(n1)

n1 = 10
n2 = 0
print(n1/n2)

print("I've sucessfully divided")

print("This is very very very important code")

n1 = 10
n2 = 2
print(n1/n2)

print("I've sucessfully divided")

"""**try and except**"""

# 
# We have handlled an error

n1 = 10
n2 = 2

try:
  print(n1//n2)
  print("sucessfully divided")
except:
  print("Error happend")

print("This is very very very important code")

"hello" + 6

(1,2,3).append(5)

n1=input("Enter Number1 : ")
n2=input("Enter Number2 : ")
try:
    print(int(n1)//int(n2))
    print("Executed !!")
except:
    print("Error !!!!!!!")
print("Sucessful")



n1 = 10
n2 = 0


try:
  print(n1//n2)
  (1,2,3).append(5)
  6 + "hello"
  print("sucessfully divided")

except ZeroDivisionError as e:
  print("I'll only support division error")
  print(e)

except AttributeError as e:
  print(e)

except Exception as e :
  print("Error happend")
  

print("This is very very very important code")

def show(): 
  try: 
    print(1)
  finally: 
    print(2)

k = show() 
print(k)

"""### User Defined Exceptions"""

name = input("Input your name : ")

try:
  if len(name)<3:
    raise Exception("Name should have more than 3 characters.")

except Exception as e:
  print(e)

try: 
  if 1 != 1: 
    raise Exception("Error")
  else: 
    print("Error has not occurred") 
except Exception: 
  print ("Error has occurred")

print("Sucessfully")

